// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ2xkMzfF9yEylWoWfy6U6hQdnuZUv7nw',
    appId: '1:360093627639:android:dd2bcf5361e1bf9b478ff2',
    messagingSenderId: '360093627639',
    projectId: 'onboarding-jan29',
    storageBucket: 'onboarding-jan29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAibXX2xg-ups5oLlPQ_i-3Do9oVYahh5o',
    appId: '1:360093627639:ios:6142caf4cb9dd7a0478ff2',
    messagingSenderId: '360093627639',
    projectId: 'onboarding-jan29',
    storageBucket: 'onboarding-jan29.appspot.com',
    iosClientId: '360093627639-prbic1lpdo5jfdtmnsfnil0pu0qstgvk.apps.googleusercontent.com',
    iosBundleId: 'i',
  );
}
